version: 2.1
jobs:
  build:
    branches:
      only:
        - master
        - development
    docker:
      - image: elixir:1.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile

  test:
    docker:
      - image: elixir:1.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix test
workflows:
  build:
    jobs:
      - build
  test:
    jobs:
      - test
